//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilene.ClientWeb.ServiceReferenceUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUser.IServiceUser")]
    public interface IServiceUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/DoWork", ReplyAction="http://tempuri.org/IServiceUser/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/DoWork", ReplyAction="http://tempuri.org/IServiceUser/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/HelloWorld", ReplyAction="http://tempuri.org/IServiceUser/HelloWorldResponse")]
        string HelloWorld(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/HelloWorld", ReplyAction="http://tempuri.org/IServiceUser/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/CreateUser", ReplyAction="http://tempuri.org/IServiceUser/CreateUserResponse")]
        void CreateUser(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUser/CreateUser", ReplyAction="http://tempuri.org/IServiceUser/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUserChannel : Pilene.ClientWeb.ServiceReferenceUser.IServiceUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUserClient : System.ServiceModel.ClientBase<Pilene.ClientWeb.ServiceReferenceUser.IServiceUser>, Pilene.ClientWeb.ServiceReferenceUser.IServiceUser {
        
        public ServiceUserClient() {
        }
        
        public ServiceUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string HelloWorld(string data) {
            return base.Channel.HelloWorld(data);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string data) {
            return base.Channel.HelloWorldAsync(data);
        }
        
        public void CreateUser(string data) {
            base.Channel.CreateUser(data);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string data) {
            return base.Channel.CreateUserAsync(data);
        }
    }
}
